# Caelon Goode
# 03/03/2025
# P1HW2
#Write program that will question user on travel expenses
#This program will ask the user to input a series of different values in order to calculate their travel expenses
print("This program will help you to calculate your travel expenses!")
print("")
print("What is your budget? ", end=(""))
budget= int(input())
print("")
print("What is your travel desitnation? ", end=(""))
destination= input()
print("")
print("How much do you think you will spend on gas? ", end=(""))
gas= int(input())
print("")
print("Approximately, how much will you need for accomodation/hotel? ", end=(""))
accomodation= int(input())
print("")
print("Lastly, how much do you think your will spend for food? ", end=(""))
food= int(input())
print("")
print("----------Travel Expenses----------")
print("Location: ", end=(""))
print(destination)
print("Intial Budget: ", end=(""))
print(budget)
print("")
print("Fuel: ", end=(""))
print(gas)
print("Accomodation: ", end=(""))
print(accomodation)
print("Food: ", end=(""))
print(food)
print("")
print("Remaining Balance: ", end=(""))
remaining_balance= budget-(gas+accomodation+food)
print(remaining_balance)
