#Caelon Gooden
#10/2/2023
#P2HW1
#Edit and enhance existing program
print("This program will help you to calculate your travel expenses!")
print("")
print("What is your budget? ", end=(""))
budget= int(input())
print("")
print("What is your travel desitnation? ", end=(""))
destination= input()
print("")
print("How much do you think you will spend on gas? ", end=(""))
gas= int(input())
print("")
print("Approximately, how much will you need for accomodation/hotel? ", end=(""))
accomodation= int(input())
print("")
print("Lastly, how much do you think your will spend for food? ", end=(""))
food= int(input())
print("")
print("----------Travel Expenses----------")
print(f"{'Location:':<20}", end="")
print(destination)
print(f"{'Intial Budget:':<20}", end=(""))
print(f"${budget:.2f}")
print(f"{'Fuel:':<20}", end=(""))
print(f"${gas:.2f}")
print(f"{'Accomodation:':<20}", end=(""))
print(f"${accomodation:.2f}")
print(f"{'Food:':<20}", end=(""))
print(f"${food:.2f}")
print("-----------------------------------")
print("Remaining Balance: ", end=(""))
remaining_balance= budget-(gas+accomodation+food)
print("")
print(f"${remaining_balance:.2f}")

